---
abstract: 'Cross-platform modular flashcard GUI application'
author:
  - 'Christian Walde <mithaldu@yahoo.de>'
build_requires:
  DBI: 0
  ExtUtils::MakeMaker: 6.42
  File::HomeDir: 0
  File::ShareDir: 0
  File::Spec::Functions: 0
  Module::Find: 0
  Module::Install::Share: 0
  Test::More: 0
  Time::HiRes: 0
  Wx: 0
  Wx::Perl::ListCtrl: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Quiz-Flashcards
no_index:
  directory:
    - inc
    - share
    - t
requires:
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
